chores/blueprints/database.py
'''Database functions

TODO(Connor): Even more database stuff.'''
import sqlite3
import os
from flask import g, Blueprint

DATABASE = Blueprint("database", __name__, template_folder="templates")

def connect_db():
  """Connect to the database file

  Args: None

  Returns: database info."""
  row = sqlite3.connect(os.path.join(DATABASE.root_path, "chores.db"))
  row.row_factory = sqlite3.Row
  return row

def get_db():
  """Fetches database for reading and writing

  Args: None

  Returns: database."""
  if not hasattr(g, "sqlite_db"):
    g.sqlite_db = connect_db()
  return g.sqlite_db

chores/blueprints/main_pages.py
'''Displays main pages

TODO(Connor): Add more pages to this, not just index.
TODO(Connor): Or migrate to chores.py.'''
from flask import Blueprint, render_template

MAIN_PAGES = Blueprint("main_pages", __name__, template_folder="templates")

@MAIN_PAGES.route("/")
def index():
  '''Displays index page.'''
  return render_template("index.html", title="Home")

chores/blueprints/user.py
'''User management

User admin page, user edit page, adding/removing users, logging in/out

TODO(Connor): Improve remove user double check.'''

from flask import Flask, Blueprint, render_template, \
  abort, session, request, redirect, url_for
from flask_bcrypt import Bcrypt
import chores.blueprints.database as DATABASE

USER = Blueprint("user", __name__, template_folder="templates")

APP = Flask(__name__)
BCRYPT = Bcrypt(APP)

@USER.route("/admin")
def show_admin():
  '''Show admin page if logged in and admin

  Renders admin.html template file, passes userlist to it.'''
  if not session.get("logged_in") or not session.get("admin"):
    abort(401)
  data = DATABASE.get_db()
  cur = data.execute("SELECT username, admin, root FROM users ORDER BY id")
  userlist = cur.fetchall()
  return render_template("admin.html", title="Admin Panel", users=userlist)

@USER.route("/adduser", methods=["POST"])
def add_user():
  '''Add user function

  Args (over POST):
    str: password
    str: confirm
    bool: admin
    str: username

  Redirects to the show_admin page.'''
  if not session.get("logged_in") and not session.get("admin"):
    abort(401)

  if request.form["password"] != request.form["confirm"]:
    return redirect(url_for("user.show_admin"))

  data = DATABASE.get_db()
  hashed = BCRYPT.generate_password_hash(request.form["password"])
  admin = bool(request.form.getlist("check"))

  insert = [request.form["username"].lower(), admin, hashed, False]
  data.execute("INSERT INTO users (username, admin, hash, root) VALUES (?, ?, ?, ?)", insert)
  data.commit()
  return redirect(url_for("user.show_admin"))

@USER.route("/login", methods=["GET", "POST"])
def login():
  '''User login page and function

  Args (over POST):
    str: username
    str: password

  If successful POST, redirect to DATABASE page.
  If failure POST, redirect to same page

  If over GET, display login page.'''
  error = None
  if request.method == "POST":
    data = DATABASE.get_db()
    cur = data.execute("SELECT username, hash, admin, root FROM users WHERE username = '%s'" % request.form["username"].lower())

    users = cur.fetchall()
    if not users:
      error = "Invalid username or password!"
      return render_template("login.html", error=error)

    user_list = users[0]

    if not BCRYPT.check_password_hash(user_list[1], request.form["password"]):
      error = "Invalid username or password!"
    else:
      session["logged_in"] = True
      session["username"] = request.form["username"].lower()

      session["admin"] = bool(user_list[2] == 1)
      session["root"] = bool(user_list[3] == 1)

      return redirect(url_for("main_pages.index"))
  return render_template("login.html", error=error, title="Login")

@USER.route("/logout")
def logout():
  '''Logs out the user
  Removes session["logged_in"] and session["admin"]

  Redirects to DATABASE page.'''
  session.pop("logged_in", None)
  session.pop("admin", None)
  return redirect(url_for("main_pages.index"))

@USER.route("/user/<username>")
def user_page(username):
  '''Displays user edit page.

  Only allow current logged in user to view their page if not admin
  If admin, show any user pages.

  Pass user admin flag to user.html template to render.'''
  if not session["logged_in"]:
    abort(401)
  if not session["admin"] and username != session["username"]:
    abort(401)

  data = DATABASE.get_db()
  admin_check = data.execute("SELECT admin FROM users WHERE username = '%s'" % username).fetchall()[0][0]
  return render_template("user.html", title="Edit "+username, user=username, admin=admin_check)

@USER.route("/user/<username>/edit", methods=["POST"])
def edit_user(username):
  '''Edit user information from user_page

  Args:
    str: password
    str: confirm
    bool: admin

  Set password and/or set admin flag on user
  Only allow admin flag change if logged in user is admin.'''
  if not session["logged_in"]:
    abort(401)
  if not session["admin"] and username != session["username"]:
    abort(401)

  if request.form["password"] != request.form["confirm"]:
    return redirect(url_for("user.user_page", username=username))

  data = DATABASE.get_db()
  root = data.execute("SELECT root FROM users WHERE username = '%s'" % username).fetchall()[0][0]
  if request.form["password"] and request.form["confirm"]:
    if request.form["password"] == request.form["confirm"]:
      hashed = BCRYPT.generate_password_hash(request.form["password"])
      data.execute("UPDATE users SET hash = ? WHERE username = '%s'" % username, [hashed])

  if session["admin"] or root == 1:
    if request.form.getlist("check") or root == 1:
      data.execute("UPDATE users SET admin = 1 WHERE username = '%s'" % username)
    else:
      data.execute("UPDATE users SET admin = 0 WHERE username = '%s'" % username)

  data.commit()
  return redirect(url_for("user.user_page", username=username))

@USER.route("/user/<username>/delete")
def delete_user(username):
  '''Asks for confirmation then deletes user

  Display a simple page for a confirm, with a bool in the URL for confirm

  Args (over GET):
    bool: confirm

  If confirmed, delete user from DATABASE.'''
  if not session["logged_in"] and not session["admin"]:
    abort(401)

  if request.args.get("confirm") == "False":
    return "Are you sure you want to delete user " + username + "? <a href=" + url_for("user.delete_user", username=username, confirm=True) + ">Yes</a>, <a href=" + url_for("user.show_admin") + ">No</a>"
  elif request.args.get("confirm") == "True":
    data = DATABASE.get_db()
    check = data.execute("SELECT root FROM users WHERE username = '%s'" % username)
    root = check.fetchall()
    if root[0][0] == 1:
      data.commit()
      return redirect(url_for("user.show_admin"))

    data.execute("DELETE FROM users WHERE username = '%s'" % username)
    data.commit()
    return redirect(url_for("user.show_admin"))
    

chores/templates/admin.html
{% extends "layout.html" %}
{% block body %}
    <form action="{{ url_for('user.add_user') }}" method=post class=add-entry>
        <dl>
            <dt>Username:
            <dd><input type=text size=30 name=username>
            <dt>Password:
            <dd><input type=password name=password id=password>
            <dt>Confirm Password:
            <dd><input type=password name=confirm id=confirm onkeyup="check();"><span id="message"></span>
            <dt>Admin?
            <dd><input type=checkbox name="check" value="is_admin" >
            <dd><input type=submit text="Add User">
        </dl>
    </form>

    <ul class=users>
    <table>
        <tr>
            <th>Username</th>
            <th>Admin</th>
        </tr>
    {% for entry in users %}
        <tr>
            <td>{{ entry.username }}</td>
            <td>{% if entry.Admin == 1 %} True {% else %} False {% endif %}</td>
            <td><a href="{{ url_for('user.user_page', username=entry.username) }}">Edit User</a></td>
            <td>{% if entry.root == 0 %}<a href="{{ url_for('user.delete_user', username=entry.username, confirm=False) }}">Delete User</a>{% endif %}</td>
        </tr>
    {% endfor %}
    </table>
    </ul>
{% endblock %}

chores/templates/index.html
{% extends "layout.html" %}

chores/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <title>{{title}} - Chores</title>
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <header>
        <a href="{{ url_for('main_pages.index') }}"><h1>Chores Tracker</h1></a>
        <h2>{{ title }}</h2>
    </header>
    <div id="login">
        {% if session.logged_in %}
            Logged in as: <a href="{{url_for('user.user_page', username=session.username) }}">{{ session.username }}</a><br />
            {% if session.admin %}<a href="{{ url_for('user.show_admin') }}">Admin Page</a>{% endif %}
            <a href="{{ url_for('user.logout') }}">Log Out</a>
        {% else %}
            <a href="{{ url_for('user.login') }}">Log In</a>
        {% endif %}
    </div>
    <nav>
        
    </nav>
    <div id="content">
        {% block body %}{% endblock %}
    </div>
</body>
</html>

chores/templates/login.html
{% extends "layout.html" %}
{% block body %}
    {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
    <form action="{{ url_for('user.login') }}" method=post>
        <dl>
            <dt>Username:
            <dd><input type=text name=username>
            <dt>Password:
            <dd><input type=password name=password>
            <dd><input type=submit value=Login>
        </dl>
    </form>
{% endblock %}

chores/templates/user.html
{% extends "layout.html" %}
{% block body %}
<form action="{{ url_for('user.edit_user', username=user) }}" method=post class=add-entry>
    <dl>
        <dt>New password:
        <dd><input type=password name=password>
        <dt>Confirm password:
        <dd><input type=password name=confirm>
        {% if session.admin %}
            <dt>Admin?
            <dd><input type=checkbox name="check" value="is_admin" {% if admin %}checked{% endif %}>
        {% endif %}
        <dd><input type=submit text="Edit User">
    </dl>
</form>
{% endblock %}